# Generated by Django 3.1.7 on 2022-10-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='geo_location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
